### PR TITLE
Cleanup, Refactor, Serverless

### PR DESCRIPTION
**Pull request by tokongs**
I am sorry for this big PR, and I am sorry for not being good a splitting my commits into smaller files.

# Changes
* Move client into the folder called frontend
* Move api into the folder called backend
* Split up the api into multiple files
* Remove redunant docker files
* Add working docker files
* Edit readme
* Add setup for Serverless
* General cleanup and code quality
* Remove drone config
* Add github actions config
* Change name of environment variables

### CODE REVIEW

**Comment by MittBrukernavn** [comment]
Just for clarification: should I review this PR or will dotkom handle it internally moving forwards?

**Comment by tokongs** [comment]
> Just for clarification: should I review this PR or will dotkom handle it internally moving forwards?

The more people looking at it the better I guess, so feel free to add a review! 
If there is any changes you are unhappy with just let me know, as this has mainly been "your" project :)

**Comment by MittBrukernavn** [comment]
Looks good to me, happy that someone cleaned up the API (I did not design it very cleanly). Feedback will consist entirely of me being nitpicky, so what you choose to fix is at your own discretion.

If you want some nitpicking: both frontend/.dockerignore and backend/.dockerignore contain Dockerfile.prod, which no longer exists. Could be worth removing to avoid confusion.

If you want a lot of nitpicking: ports are written differently in db than in frontend/backend of the docker-compose file (the db service has them with singlequotes, the other two with no quotes).

If you require silly levels of nitpicking: the word "paralell" isn't always spelled correctly. I'm guessing this is just an old mistake that I'm noticing after you refactored, but I noticed the word "paralell" coming up a lot. Should be either "parallel" (english) or "parallell" (norwegian).

This is really all I could find. Great work! 😄

**Comment by kharann** [comment]
yep yep, hep hep, looks good to me. I totally read everything :^)

**Comment by tokongs** [comment]
Thanks for the feedback, I appreciate it! :+1: 
I will try to fix the things you mentioned, they seem like easy fixes.

**Pull request merged**
